### ISSUE TITLE
Add support for deletes in RefreshIndex for incremental mode

### ISSUE THREAD

**Issue by pirz** [microsoft/hyperspace#105]
### Describe the issue
Once some files or partitions are removed from source data, fix the index and remove corresponding index records from the index. This action is triggered by calling `refreshIndex` API.

**Overview.**
Using index metadata, we find which data files are removed.
Using lineage in index, we can find index records which were generated from removed files' data records. We re-generate affected index files by removing such records.  

**Related Issues.**
- [x] Add Lineage to index records (issue #104) 
- [x] Remove deleted records during refresh (issue #133)
- [x] Merge refresh action for delete to index refresh (issue #149)

### To Reproduce
N/A

### Expected behavior
1. Create an index on top of some partitioned data.
2. Remove some files and/or partitions from source data.
3. Call `refreshIndex` on index.
4. Upon successful termination of refresh index, records corresponding to the deleted records from source data should no longer be present in the index and the index should be in active and usable state.

### Environment 
All environments.

**Comment by pirz** [comment]
Feature complete - All children issues are closed by corresponding PRs.
