### ISSUE TITLE
Add support for deletes in RefreshIndex for quick mode

### ISSUE THREAD

**Issue by pirz** [microsoft/hyperspace#134]
### Describe the issue
This is the parent issue to track the work of adding support for delete in quick mode.

**User Scenario.**
1. User has a dataset 
2. User uses Hyperspace to create an index 
3. User deletes an existing partition OR removes files from an existing partition
4. **Metadata Update:** User calls refresh index API in quick mode to update Index Metadata
5. **Enforce Delete during read:** Index should become usable during query time by excluding the deleted records when index is used.

During index refresh in quick mode, we do not fix the index files, but we get the list of files/partitions that were deleted (from Step 3) and write a new log entry with this diff. 
When the user now queries the data, we would get the latest state from the log and add a filter node on top of index scan to exclude index entries coming from deleted source data files.

**Related issues.**
- [x] Add Lineage to index records (Issue #104)
- [ ] Add index metadata update in RefreshIndex for quick mode (Issue #169)
- [ ] Modify Hyperspace rules to leverage an index with deleted source data files after RefreshIndex in quick mode  (Issue #174)

### To Reproduce
N/A

### Expected behavior
The scenario described above should work correctly.

### Environment 
All.
