### ISSUE TITLE
Hyperspace Index on Delta Lake

### ISSUE THREAD

**Issue by sezruby** [microsoft/hyperspace#148]
### Describe the issue

Support Hyperspace Index on Delta Lake Table
https://delta.io/

#### Retrieve source file list from Relation
* [TahoeFileIndex.scala](https://github.com/delta-io/delta/blob/master/src/main/scala/org/apache/spark/sql/delta/files/TahoeFileIndex.scala)
* TahoeFileIndex provides `def inputFiles` API; we could use the API as it handles all version & delta log related things.
```
// Both logical & phisycal plan have this "delta" information
// TahoeLogFileIndex from LogicalRelation.HaddopFsRelation.Location

> rel.location.asInstanceOf[TahoeLogFileIndex]
org.apache.spark.sql.delta.files.TahoeLogFileIndex = Delta[version=2, file:/tmp/delta-table]

> val e = rel.location.asInstanceOf[TahoeLogFileIndex]
> e.inputFiles
res19: Array[String] = Array(file:/tmp/delta-table/part-00003-e628f8cd-1609-4adb-ad46-7399bb67f666-c000.snappy.parquet, file:/tmp/delta-table/part-00003-8504e0b9-b6de-4eb8-96d1-9a0b5598faee-c000.snappy.parquet, file:/tmp/delta-table/part-00004-ca1393a7-05e8-4960-ab3f-c0cfaab9a4b7-c000.snappy.parquet, file:/tmp/delta-table/part-00004-2f5baa84-2bce-4e30-a1e9-08b36f28b8fc-c000.snappy.parquet, file:/tmp/delta-table/part-00006-52a5ce8c-e222-49ca-a8d4-e18fcd540fc9-c000.snappy.parquet, file:/tmp/delta-table/part-00007-9907856f-c231-4e17-81e9-3e65b3ec58b0-c000.snappy.parquet, file:/tmp/delta-table/part-00001-c20d1b6d-4d33-40cd-a587-204f1368726b-c000.snappy.parquet, file:/tmp/delta-table/part-00000-f0ed3f09-e749-4f6b-9855-b070175f010e-c000.snappy.parquet, file:/tmp/delt…
```

#### Create & refresh index
We could generate an index based on the given DF and path.
```
val df = spark.read.format("delta").load("/tmp/delta-table")
```

#### Issues
* [update / merge into / delete / overwrite] causes to rewrite whole data => full refresh required
* Delta lake jar dependency
* delta log retention: default 7 days

#### Things to check
* Delta streaming feature
* apply partitionFilter / dataFilter of Delta to index? 
* hybrid scan feasibility & threshold of the amount of diff
* Use version info for signature calculation?

#### TODOs (for basic functionality) 
- [ ] Delta lake soft dependency
- [ ] index creation / refreshment on a delta table
- [ ] FilterIndexRule & JoinIndexRule support
... tbd
