### ISSUE TITLE
Incremental Indexing: Support for incremental changes to index when new data is added

### ISSUE THREAD

**Issue by apoorvedave1** [microsoft/hyperspace#29]
### Describe the issue
Currently when new data is added, the indexes become obsolete. The only way to make them usable is through the `refresh()` api which recreates complete index from scratch. Add functionality to support creation of indexes only on additional new data instead of recreating from scratch.

### Expected behavior
New additional data to old data doesn't require rebuilding of indexes on complete data. Only additional data gets indexed

Intermediate issues and PRs
 * [x]  Capture source file info to detect the change of the dataset #120 
 * [x]  The root paths captured in index log entry should always be absolute paths #126 
 * [x]  Store index file names and file sizes in operation log #107
 * [x]  Add full list of index files to index log entry #103
 * [x]  Index metadata should always store absolute paths (alternate solution) #128, #127 
 * [x]  Store file name, size and modified time of index files in metadata #122
 * [x]  New Tree based Structure for index metadata #139 
 * [x]  Index merge functionality PR: #162 
 * [x]  Incremental indexing support for Append-only data #110 , PR: #163

**Comment by imback82** [comment]
Can you update the description so that the current `refresh` does a full rebuild?

**Comment by apoorvedave1** [comment]
> Can you update the description so that the current `refresh` does a full rebuild?

added description mentioning current `refresh()` does a full rebuild.

**Comment by apoorvedave1** [comment]
closed by #163
